name: Update README

on:
  push:
    branches:
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update README.md
        run: |
          owner=$(echo $GITHUB_REPOSITORY | awk -F / '{print $1}')
          repo=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
          ig_title="Your IG Title"
          ig_name="Your IG Name"

          sed "s/{OWNER}/$owner/g; s/{REPO}/$repo/g; s/{IG_TITLE}/$ig_title/g; s/{IG_NAME}/$ig_name/g" README-template.md > README.md
          
      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README.md"
          git push
